module.exports = [
    "all-time",
    "Boring Billion",
    "Variscan orogeny",
    "cat gap",
    "Paleolithic",
    "100,000-10,000 BCE",
    "Upper Paleolithic",
    "Gravettian",
    "Magdalenian",
    "stone age in Finland",
    "Suomusjärvi culture",
    "Ancient Estonia",
    "Pre-colonial history of Quebec",
    "Mesoamerican Archaic period",
    "Early Jōmon",
    "Uruk V Period",
    "Middle Jōmon",
    "Uruk IV Period",
    "Bronze Age India",
    "Minoan civilization",
    "ancient history",
    "Bronze Age Europe",
    "Uruk III Period",
    "Proto-Elamite period",
    "Early Dynastic Period of Egypt",
    "Ebla",
    "Early Dynastic period",
    "Early Dynastic I",
    "Early Dynastic II",
    "Old Kingdom of Egypt",
    "Old Elamite period",
    "Early Dynastic IIIa",
    "Mesoamerican Preclassic period",
    "Early Dynastic IIIb",
    "Late Jōmon",
    "Fifth Dynasty of Egypt",
    "Akkad period",
    "Ebla Period",
    "Linear Elamite Period",
    "Lagash II Period",
    "First Intermediate Period of Egypt",
    "Three Dynasties",
    "pre-Qin period",
    "Ur III period",
    "Middle Kingdom of Egypt",
    "Old Assyrian Empire",
    "Early Old Babylonian Period",
    "Isin-Larsa period",
    "Middle Bronze Age",
    "Old-Assyrian period",
    "Old Babylonian Period",
    "Barra phase",
    "Shang dynasty",
    "New Kingdom of Egypt",
    "Vedic period",
    "Middle Hittite Period",
    "Iron Age India",
    "Middle Assyrian Period",
    "Middle Babylonian period",
    "Middle Assyrian Empire",
    "Amarna Period",
    "Middle Elamite period",
    "Ramessides",
    "Ancient Greece",
    "Israelite period",
    "classical antiquity",
    "Early Neo-Babylonian Period",
    "Neo-Elamite period",
    "Zhou dynasty",
    "Western Zhou",
    "Woodland period",
    "Final Jōmon",
    "Early Woodland period",
    "Neo-Assyrian Empire",
    "Neo Assyrian Period",
    "Late Babylonian Period",
    "Early Horizon",
    "Archaic Greece",
    "Herrera Period",
    "VIII-VII BC",
    "VIII-VI BC",
    "VIII-V BC",
    "VIII or VII century",
    "beginning of VIII BC",
    "first half of VIII BC",
    "second quarter of VIII BC",
    "mid VIII BC",
    "Spring and Autumn period",
    "Eastern Zhou",
    "Spring and Autumn Warring States Period",
    "Roman Kingdom",
    "First Roman Kingdom",
    "Early Scythian period",
    "third quarter of VIII BC",
    "second half of VIII BC",
    "third quarter of VI BC",
    "Syrakousai",
    "late VIII BC",
    "VII BC - VI BC",
    "VII BC - V BC",
    "VII BC - IV BC",
    "first half of VII BC",
    "second quarter of VII BC",
    "mid VII BC",
    "second half of VII BC",
    "third quarter of VII BC",
    "Ancient Greek colonization of the Northern Black Sea",
    "Neo Babylonian Period",
    "late VII BC",
    "late VII BC - early VI BC",
    "Second Roman Kingdom",
    "later VII BC",
    "end of VII BC",
    "Phoenicia under Babylonian rule",
    "Middle Scythian period",
    "earlier VI BC",
    "beginning of VI BC",
    "early VI BC",
    "first half of VI BC",
    "Babylonian captivity",
    "second quarter of VI BC",
    "mid VI BC",
    "Achaemenid Empire",
    "Persian period",
    "second half of VI BC",
    "Achaemenid Period",
    "Second Temple period",
    "late VI BC",
    "Second Temple Judaism",
    "later VI BC",
    "Roman Republic",
    "Early Roman Republic",
    "end of VI BC",
    "beginning of V BC",
    "earlier V BC",
    "early V BC",
    "first half of V BC",
    "Classical Greece",
    "Fifth-century Athens",
    "Warring States period",
    "second quarter of V BC",
    "mid V BC",
    "Ror imperial period",
    "La Tène period",
    "Ror Empire",
    "High Classical",
    "second half of V BC",
    "third quarter of V BC",
    "late V BC",
    "Intertestamental period",
    "later V BC",
    "end of V BC",
    "Spartan hegemony",
    "Sangam period",
    "beginning of IV BC",
    "earlier IV BC",
    "early IV BC",
    "first half of IV BC",
    "second quarter of IV BC",
    "mid IV BC",
    "Macedonian Period",
    "second half of IV BC",
    "third quarter of IV BC",
    "Greco-Roman Egypt",
    "late IV BC",
    "Hellenistic Greece",
    "later IV BC",
    "Selucid Period",
    "end of IV BC",
    "history of Ptolemaic Egypt",
    "III BC - II BC",
    "beginning of III BC",
    "earlier III BC",
    "early III BC",
    "first half of III BC",
    "second quarter of III BC",
    "mid III BC",
    "Middle Roman Republic",
    "Roman Warm Period",
    "second half of III BC",
    "third quarter of III BC",
    "Parthian Period",
    "late III BC",
    "Qin dynasty",
    "Qin Han",
    "Chinese Empire",
    "later III BC",
    "end of III BC",
    "Han dynasty",
    "Classical Rome",
    "Middle Woodland period",
    "beginning of II BC",
    "earlier II BC",
    "early II BC",
    "first half of II BC",
    "Kingdom of Artaxerxes",
    "second quarter of II BC",
    "mid II BC",
    "Samhan",
    "Proto–Three Kingdoms of Korea",
    "second half of II BC",
    "Roman Greece",
    "Late Roman Republic",
    "late II BC",
    "later II BC",
    "end of II BC",
    "Roman period in the Netherlands",
    "I BC - I AD",
    "beginning of I BC",
    "earlier I BC",
    "early I BC",
    "first half of I BC",
    "mid I BC",
    "second quarter of I BC",
    "Roman Palestine",
    "Gallo-Roman Brussels",
    "Roman Gaul",
    "third quarter of I BC",
    "second half of I BC",
    "Roman Egypt Era",
    "Pax Romana",
    "Principate",
    "Roman Empire",
    "High Roman Empire",
    "Roman Belgium",
    "Classical Roman Empire",
    "Roman imperial period",
    "late I BC",
    "Three Kingdoms of Korea",
    "later I BC",
    "end of I BC",
    "Early Christianity",
    "beginning of I AD",
    "earlier I AD",
    "early I AD",
    "first half of I AD",
    "Tiberian era",
    "Eastern Han",
    "second quarter of I AD",
    "mid I AD",
    "Kushan period",
    "second half of I AD",
    "third quarter of I AD",
    "late I AD",
    "later I AD",
    "end of I AD",
    "beginning of II AD",
    "earlier II AD",
    "early II AD",
    "first half of II AD",
    "mid II AD",
    "second quarter of II AD",
    "second half of II AD",
    "third quarter of II AD",
    "late II AD",
    "later II AD",
    "end of the Han dynasty",
    "end of II AD",
    "Early Intermediate Period",
    "Pax Kushana",
    "beginning of III AD",
    "first half of III AD",
    "Barbarian invasion of the 3rd century",
    "Three Kingdoms",
    "Wei, Jin, Southern and Northern dynasties",
    "Six Dynasties",
    "Sassanian Period",
    "second quarter of III AD",
    "Crisis of the Third Century",
    "Low Roman Empire",
    "barracks emperor",
    "Kofun period",
    "Coptic period",
    "second half of III AD",
    "third quarter of III AD",
    "Little Peace of the Church",
    "Pallava dynasty",
    "Later Roman Empire",
    "Roman Tetrarchy",
    "Dominate",
    "end of III AD",
    "Mesoamerican Classic period",
    "beginning of IV AD",
    "first half of IV AD",
    "Wu Hu luan hua",
    "Sixteen Kingdoms",
    "Barbarian invasions of the 4rd century",
    "second quarter of IV AD",
    "Holy Land during Byzantine rule",
    "second half of IV AD",
    "third quarter of IV AD",
    "Greek late classical period",
    "Migration Period",
    "end of IV AD",
    "Byzantine Empire",
    "400-1499",
    "Decline of Greco-Roman polytheism",
    "Pax Gupta",
    "sub-Roman Britain",
    "beginning of V AD",
    "earlier V AD",
    "early V AD",
    "first half of V AD",
    "Northern and Southern dynasties",
    "Southern dynasties",
    "mid V AD",
    "second quarter of V AD",
    "Northern dynasties",
    "Anglo-Saxon London",
    "second half of V AD",
    "third quarter of V AD",
    "Dark period of the Kingdom of the Suebi",
    "Middle Ages",
    "Merovingian Period",
    "late V AD",
    "Greek early classical period",
    "Merovingian Brussels",
    "later V AD",
    "Carolingian Brussels",
    "end of V AD",
    "Early Middle Ages",
    "Jahiliyyah",
    "Anglo-Saxon period",
    "Early Middle Ages in the Iberian Peninsula",
    "Late Woodland period",
    "Period of Integration",
    "earlier VI AD",
    "early VI AD",
    "beginning of VI AD",
    "first half of VI AD",
    "mid VI AD",
    "second quarter of VI AD",
    "Byzantine Papacy",
    "Asuka period",
    "classical Japan",
    "second half of VI AD",
    "third quarter of VI AD",
    "late VI AD",
    "Sui Tang",
    "Mid-Imperial China",
    "later VI AD",
    "end of VI AD",
    "Suiko period",
    "Middle Horizon",
    "Central Javanese Period",
    "Medieval India",
    "anglian",
    "beginning of VII AD",
    "earlier VII AD",
    "early VII AD",
    "first half of VII AD",
    "Byzantine Empire under the Heraclian dynasty",
    "Tang dynasty",
    "Muhammad in Medina",
    "second quarter of VII AD",
    "mid VII AD",
    "early Islamic period in Palestine",
    "ancient times",
    "Byzantine Dark Ages",
    "second half of VII AD",
    "third quarter of VII AD",
    "Administrative policies of Ali",
    "late VII AD",
    "later VII AD",
    "end of VII AD",
    "Twenty Years' Anarchy",
    "North South States Period",
    "early VIII AD",
    "earlier VIII AD",
    "beginning of VIII AD",
    "first half of VIII AD",
    "Nara period",
    "Moorish Gibraltar",
    "Byzantine Empire under the Isaurian dynasty",
    "second quarter of VIII AD",
    "mid VIII AD",
    "four-character era name period",
    "second half of VIII AD",
    "third quarter of VIII AD",
    "Frankish Papacy",
    "late VIII AD",
    "later VIII AD",
    "end of VIII AD",
    "Vikings",
    "Viking Age",
    "Heian period",
    "Early Heian Period",
    "Gurjara-Pratihara",
    "Medieval Abkhazia",
    "norse era",
    "Anglo-Scandinavian",
    "Khmer Empire",
    "Byzantine Empire under the Nikephorian dynasty",
    "Iranian Intermezzo",
    "Era of Fragmentation",
    "Lotharingian Brussels",
    "Anarchy at Samarra",
    "Middle Heian Period",
    "Portugal in the Reconquista",
    "Later Three Kingdoms",
    "Norse colonization of North America",
    "Pala dynasty (Kamarupa)",
    "Ikhshidid Egypt",
    "Five Dynasties",
    "Five Dynasties and Ten Kingdoms Period",
    "Liao Song Xia Jin Yuan",
    "Goryeo period",
    "Eastern Javanese Period",
    "Ngô dynasty",
    "Medieval Warm Period",
    "Song Liao Jin Xia",
    "Northern Song dynasty",
    "Fatimid Egypt",
    "Reginarid Brussels",
    "High Middle Ages",
    "Ottonian art",
    "Late Intermediate Period",
    "Mesoamerican Postclassic period",
    "Shi'a Century",
    "taifa (first period)",
    "Later Heian Period",
    "History of the papacy from 1048 to 1257",
    "Byzantine Empire under the Doukas dynasty",
    "England in the High Middle Ages",
    "Byzantine Empire under the Komnenos dynasty",
    "Komnenian restoration",
    "Heian Insei Period",
    "Nizari Ismaili state",
    "Proto-Renaissance",
    "age of the Communes",
    "Period of Appanages",
    "Saladin in Egypt",
    "Kamakura period",
    "Byzantine Empire under the Angelos dynasty",
    "Early Kamakura Period",
    "Frankokratia",
    "Middle Kamakura Period",
    "Mongol Armenia",
    "Interregnum of the Holy Roman Empire (1245–1273)",
    "Folkunga Dynasty",
    "Mamluk Palestine",
    "Byzantine Empire under the Palaiologos dynasty",
    "Tibet under Yuan administrative rule",
    "Yuan dynasty",
    "Yuan Ming Qing",
    "federation of three cantons",
    "rise of the Ottoman Empire",
    "Later Kamakura Period",
    "Pax Mongolica",
    "Late Middle Ages",
    "Bunpō",
    "Sanzan period",
    "federation of eight cantons",
    "Kenmu Restoration",
    "Muromachi period",
    "Nanboku-chō period",
    "Phagmodrupa dynasty",
    "Ming dynasty",
    "Ming Qing",
    "Burgundian Netherlands",
    "Early Joseon Period",
    "Early Muromachi Period",
    "Ottoman Bulgaria",
    "Burgundian Brussels",
    "Early Renaissance",
    "Dual monarchy of England and France",
    "Chaktomuk era",
    "Middle Muromachi Period",
    "Ottoman Greece",
    "Castilian Gibraltar",
    "Sengoku period",
    "Late Horizon",
    "Federation of thirteen cantons",
    "Habsburg Netherlands",
    "Habsburg Brussels",
    "Tudor Wales",
    "Tudor period",
    "Cossack Age of Ukraine",
    "France in the early modern period",
    "Later Muromachi Period",
    "US Colonial Period",
    "Spanish colonization of the Americas",
    "High Renaissance",
    "Portuguese Mozambique",
    "1500-1749",
    "Cossack Age",
    "Age of Discovery"
];
